// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransporteEscolarAPI.Data;

#nullable disable

namespace TransporteEscolarAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531024528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransporteEscolarAPI.Models.Acudiente", b =>
                {
                    b.Property<int>("IdAcudiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_acudiente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAcudiente"));

                    b.Property<string>("DireccionResidencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion_residencia");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdAcudiente");

                    b.ToTable("acudiente");
                });

            modelBuilder.Entity("TransporteEscolarAPI.Models.Conductor", b =>
                {
                    b.Property<int>("IdConductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_conductor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConductor"));

                    b.Property<string>("CategoriaLicencia")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("categoria_licencia");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_licencia");

                    b.HasKey("IdConductor");

                    b.ToTable("conductor");
                });

            modelBuilder.Entity("TransporteEscolarAPI.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Colegio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colegio");

                    b.Property<string>("CursoGrado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("curso_grado");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<int>("IdAcudiente")
                        .HasColumnType("integer")
                        .HasColumnName("id_acudiente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstudiante");

                    b.ToTable("estudiante");
                });

            modelBuilder.Entity("TransporteEscolarAPI.Models.Historial", b =>
                {
                    b.Property<int>("IdViaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_viaje");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdViaje"));

                    b.Property<string>("EstadoViaje")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_viaje");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("IdConductor")
                        .HasColumnType("integer")
                        .HasColumnName("id_conductor");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo");

                    b.Property<decimal?>("LatitudActual")
                        .HasColumnType("numeric")
                        .HasColumnName("latitud_actual");

                    b.Property<decimal?>("LongitudActual")
                        .HasColumnType("numeric")
                        .HasColumnName("longitud_actual");

                    b.HasKey("IdViaje");

                    b.ToTable("historial");
                });

            modelBuilder.Entity("TransporteEscolarAPI.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("TransporteEscolarAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("TransporteEscolarAPI.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("CapacidadPasajeros")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_pasajeros");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("placa");

                    b.Property<DateTime?>("SoatVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soat_vencimiento");

                    b.Property<DateTime?>("TecnomecanicaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tecnomecanica_vencimiento");

                    b.HasKey("IdVehiculo");

                    b.ToTable("vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
