name: Deploy SchoolTrack Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.16.0'

      - name: Instalar dependencias
        working-directory: ./Frontend/transporte-escolar-web
        run: npm install

      - name: Generar build React
        working-directory: ./Frontend/transporte-escolar-web
        run: npm run build

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Subir dist al servidor Apache
        run: |
          rsync -avz --delete \
          ./Frontend/transporte-escolar-web/dist/ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/seminario1/schooltrack/
