name: Deploy SchoolTrack Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar paquetes
        working-directory: ./Backend/TransporteEscolarAPI
        run: dotnet restore

      - name: Publicar Backend
        working-directory: ./Backend/TransporteEscolarAPI
        run: dotnet publish -c Release -o ./publish

      - name: Configurar SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          if [ -z "$SSH_KEY" ]; then
            echo "ERROR: SSH_PRIVATE_KEY no está configurado en GitHub Secrets."
            exit 1
          fi
          if [ -z "$SERVER_IP" ]; then
            echo "ERROR: SERVER_IP no está configurado en GitHub Secrets."
            exit 1
          fi
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Crear carpeta backend
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            mkdir -p /home/schooltrack/backend
          "

      - name: Subir backend
        run: |
          rsync -avz --delete \
          ./Backend/TransporteEscolarAPI/publish/ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/schooltrack/backend/

      - name: Ejecutar Migraciones de Entity Framework
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/schooltrack/backend
            sudo -u schooltrack /home/schooltrack/bin/dotnet exec /home/schooltrack/backend/TransporteEscolarAPI.dll --ef-database-update
          "

      - name: Reiniciar API
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            sudo systemctl restart schooltrack
          "