name: Deploy SchoolTrack Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar paquetes
        working-directory: ./Backend/TransporteEscolarAPI
        run: dotnet restore

      - name: Publicar Backend
        working-directory: ./Backend/TransporteEscolarAPI
        run: dotnet publish -c Release -o ./publish

      - name: Crear carpeta SSH
        run: mkdir -p ~/.ssh

      - name: Crear llave privada
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Agregar host conocido
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Crear carpeta backend
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            mkdir -p /home/schooltrack/backend
          "

      - name: Subir backend
        run: |
          rsync -avz --delete \
          ./Backend/TransporteEscolarAPI/publish/ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/schooltrack/backend/

      - name: Ejecutar migraciones EF
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            export PATH=\$PATH:/home/schooltrack/.dotnet/tools
            cd /home/schooltrack/backend
            /home/schooltrack/bin/dotnet ef database update
          "

      - name: Reiniciar API
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            sudo systemctl restart schooltrack
          "